cache:
  paths:
    - target
stages:
  - publish
  - build
  - Sonar_QG
  - deploy_to_dev
  - deploy_to_dit
  - deploy_to_ge1
  - deploy_to_perf
  
Sonar:
  stage: publish
  script:
    - cd C:\Users\Pavithra_R6\Downloads\sonarqube-7.3\sonarqube-7.3\bin\windows-x86-64
    - StartNTService.bat
  tags:
    - shell
  only:
  - QA

maven_build:
  stage: build
  tags:
    - shell
  script:
    
    - echo "Building project with maven"
    - mvn clean install sonar:sonar -Dsonar.host.url=http://localhost:9005 -Dsonar.projectKey=sample -Dsonar.projectName=sample -Dsonar.projectVersion=0.3
    #- export PACKAGE_VERSION=$(cat version)
    #- echo "Package: $PACKAGE" 
  artifacts:
    name: $CI_VERSION
    paths:
      - target/TestLabOne-0.0.2-SNAPSHOT.jar
  only:
  - QA
  environment:
    name: artifact_save

Sonar_QG:
  stage: Sonar_QG
  variables:
    qualitygate: "waitForQualityGate()"
  script: (if [$qualitygate.status NEQ "OK"]; echo "Pipeline aborted due to quality gate coverage failure:${qualitygate.status}" ; fi )
  tags:
    - shell
  only:
  - QA


deploy_to_dev:
  stage: deploy_to_dev
  script:
    - cf login -a api.sausvdc02.pcf.dell.com -u %CF_USERNAME% -p %CF_PASSWORD% -s DEV
    - cf push 
  tags:
    - shell
  dependencies:
  - maven_build
  only:
  - master
  environment:
    name: dev
  
deploy_to_dit:
  stage: deploy_to_dit
  script:
    - cf login -a api.sausvdc02.pcf.dell.com -u %CF_USERNAME% -p %CF_PASSWORD% -s DIT
    - cf push 
  tags:
    - shell
  dependencies:
  - maven_build
  only:
  - master

deploy_to_re1:  
  stage: deploy_to_ge1
  script:
    - cf login -a api.sausvdc02.pcf.dell.com -u %CF_USERNAME% -p %CF_PASSWORD% -s GE1
    - cf push 
  
  tags:
    - shell
  dependencies:
  - maven_build
  #when: manual
  only:
  - master
  
deploy_to_perf:
  stage: deploy_to_perf
  #approvers:
    #- Harish_Hegde
  #approvals_required: 1
  script:
    - cf login -a api.sausvdc02.pcf.dell.com -u %CF_USERNAME% -p %CF_PASSWORD% -s GE2
    - cf push 
  tags:
    - shell
  dependencies:
  - maven_build
  #when: manual
  only:
  - master
  environment:
    name: production

  

  
  



